### ISSUE TITLE
Request for License in Repository

### ISSUE THREAD

**Issue by krushnarout** [kartikeysingh6/kartik_python#73]
Hello there, 

I noticed that this repository does not have a clear and explicit license mentioned. Having a clear and appropriate license is essential for governing how the code and any associated assets can be used, modified, and distributed.

A proper license not only protects the interests of the authors and contributors but also provides legal clarity to users and potential collaborators. It's important for promoting collaboration, ensuring proper attribution, and avoiding any legal ambiguities.

I'd be happy to create a License for this repository.

Thank you!

**Comment by kartikeysingh6** [comment]
Sure!
