### ISSUE TITLE
I want to make a django website to track vaccination centers around us and get the route to reach the center

### ISSUE THREAD

**Issue by shayan-cyber** [kartikeysingh6/kartik_python#8]
It is developed using django, js, GoogleMaps API, mapquest API

**Comment by kartikeysingh6** [comment]
Okay, so what do you expect from me?

**Comment by shayan-cyber** [comment]
> Okay, so what do you expect from me?

since this repo is under hacktoberfest I would like to contribute

**Comment by kartikeysingh6** [comment]
Yeah sure, just start sending PRs

**Comment by shayan-cyber** [comment]
> Yeah sure, just start sending PRs

yeah the project is done, I'll add the project and create the PR
